---
title: "Workshop"
output: 
  html_document:
    includes: 
      in_header: 
      - hero-image.html
---



Date: Monday, November 8th
Time: noon -- 4:00pm ET


FIA produces estimates of numerous forest attributes in a variety of domains, with post-stratification as the primary estimation method. As technological and statistical advances provide both new data sources and new modeling techniques, estimation procedures must adapt to accommodate these advances. Effectively combining data collected under a complex sampling design with new sources of auxiliary data has the potential to greatly increase the efficiency of our estimators. Luckily, how to best leverage these multiple data sources has been a vibrant area of recent survey research.

This workshop will introduce participants to one modern, model-assisted approach to survey estimation, where predictive models serve as the key link between the FIA plot data and auxiliary data. This method will cover a broad class of predictive models, including generalized linear models, regularized (elastic net) regression, and regression trees. The workshop will also include demonstrations of how to estimate forest attributes in the statistical software R, using the `mase` package.  


[This `R` script](https://mcconvil.github.io/IMS21_ML_Surveys/mase_R.R) contains all the code used in the `mase` slide deck.
